### ISSUE TITLE
thanks! and how about hit "try again" button?

### ISSUE THREAD

**Issue by dadenday** [nneonneo/2048-ai#30]
can you make it hits "continues" slower when the game wins at 2048? like when the game won and shown 2 button "continues & try again", it would delays 1 second or more to hit the button for ppl to check out the result?
maybe pause; stop or hit "try again" instead?
btw, I'm really thankful to use this great AI

**Comment by nneonneo** [comment]
@dadenday: You just need to change `continue_game` to `restart_game` (the latter performs the equivalent of hitting the "try again" button).
