### ISSUE TITLE
Speed and more stable

### ISSUE THREAD

**Issue by mceyhan** [nneonneo/2048-ai#32]
Hi my friends thanks for coding this.

i wonder can you make this code for bitcoin2048 ? it has to be slowlier (because of capctha trap).
and it gets slowlier working by working. when it reaches 4096 , firefox gets crashed.

im using windows, what do you think about this?

**Comment by nneonneo** [comment]
The Firefox crash is due to a conflict between recent Firefox versions and the official FF-Remote-Control. To resolve it, you can use my fork of FF-Remote-Control: https://github.com/nneonneo/FF-Remote-Control
