### ISSUE TITLE
New Game after reached 4096

### ISSUE THREAD

**Issue by mceyhan** [nneonneo/2048-ai#33]
Hi my friends thanks for coding this.

i wonder can you make this code when it reached 4096 and turn back to work again ? 

what do i have to modify?

**Comment by mceyhan** [comment]
back to work i mean a new game

**Comment by nneonneo** [comment]
See #32: the slowdown you're seeing is due to FF-Remote-Control, not the AI.

**Comment by mceyhan** [comment]
i asked after 4096 a new game
