### ISSUE TITLE
Guess RNG state

### ISSUE THREAD

**Issue by SoniEx2** [nneonneo/2048-ai#36]
Just a thought, but couldn't you guess the RNG state, and use that for better predictions?

**Comment by nneonneo** [comment]
Sure, but that's verging on cheating :) Plus, the RNG used is browser and OS dependent.

**Comment by SoniEx2** [comment]
All RNGs have patterns. Just find the pattern.

**Comment by nneonneo** [comment]
Not going to happen, sorry. Feel free to make a fork in which you guess the RNG state ;)
