### ISSUE TITLE
4D 2048 AI?

### ISSUE THREAD

**Issue by f000bar** [nneonneo/2048-ai#4]
This is amazing, thanks!
Do you have any interest in modifying it/making a version that could do the 4D version? http://huonw.github.io/2048-4D/?
I'd try it myself, but my coding abilities are extremely limited.

**Comment by nneonneo** [comment]
FYI: I added support for the 4D game in a branch, if you're still interested.

**Comment by veleritas** [comment]
I've got a working 4D solver [here](https://github.com/veleritas/4d_2048).

I'm still working on optimizing the heuristics, but so far in internal tests the best results I have managed to achieve are as follows:

Performance stats for 200 games:
Got to 2^11 (2048) 200 times (100.00%)
Got to 2^12 (4096) 200 times (100.00%)
Got to 2^13 (8192) 190 times (95.00%)
Got to 2^14 (16384) 124 times (62.00%)
Got to 2^15 (32768) 7 times (3.50%)

**Comment by DMarke99** [comment]
I have also developed a solver for 2048-4D [here](https://github.com/DMarke99/2048-4d-ai)

Performance observed over 100 games:
|Tile|Proportion of games <br /> tile achieved|
|:-:|:-:|
|2048|100%|
|4096|98%|
|8192|98%|
|16384|96%|
|32768|87%|
|65536|15%|

Min Score: 36924, Median Score: 845132.0, Max Score: 2212500

Coefficient of the heuristics and model parameters were tuned by hand so there is still room for improvement in this despite its high performance.
