### ISSUE TITLE
Visual studio build 32-bit causes issue for 64-bit computer

### ISSUE THREAD

**Issue by whycare** [nneonneo/2048-ai#43]
The build with visual studio creates a 32-bit ddl.
On 64-bit computers with python as a 64-bit programme,
this causes a problem with python loading 2048.ddl .

**Comment by nneonneo** [comment]
You should be able to build a 64-bit DLL by opening a 64-bit Visual Studio command-line prompt (for example, this is called "VS2015 x64 Native Tools Command Prompt" for Visual Studio 2015), and running `make-msvc.bat` from there.
