### ISSUE TITLE
Getting error when running 2048.py

### ISSUE THREAD

**Issue by dfoverdx** [nneonneo/2048-ai#46]
I'm running Windows 10.  I followed the directions in `README.md`, opening Developer Command Prompt for VS2015 as administrator, and building with `make-msvc.bat`, which seemed to run fine.  Running `2048.py` the first time told me I was missing python's websocket-client, so I installed that with `pip install websocket-client`.  

I started chrome, `chrome --remote-debugging-port=9222`, and ran the following:

```
D:\src\2048-ai>2048.py -b chrome -p 9222
Select a page to attach to:
1) GitHub - nneonneo/2048-ai: AI for the 2048 game
2) 2048
3) Adblock Plus
Selection? 2
Traceback (most recent call last):
  File "D:\src\2048-ai\2048.py", line 149, in <module>
    exit(main(sys.argv[1:]))
  File "D:\src\2048-ai\2048.py", line 140, in main
    gamectrl = Hybrid2048Control(ctrl)
  File "D:\src\2048-ai\gamectrl.py", line 10, in __init__
    self.setup()
  File "D:\src\2048-ai\gamectrl.py", line 67, in setup
    ''')
  File "D:\src\2048-ai\chromectrl.py", line 92, in execute
    if resp['wasThrown']:
KeyError: 'wasThrown'
```

I'm a little lost on what to do next to troubleshoot.  Help?

**Comment by nneonneo** [comment]
Thanks for the bug report - the Chrome devs removed the wasThrown key from the debugging API, so I updated the code to deal with it.
