### ISSUE TITLE
Something wrong when I try to build it on os x

### ISSUE THREAD

**Issue by kgcrandn** [nneonneo/2048-ai#47]
Here is the information:
make: execvp: ./install-sh: Permission denied
g++  -g -O2 -std=gnu++11 -O3 -Wall -Wextra -fPIC -c -o bin/2048.o 2048.cpp
error: unable to open output file 'bin/2048.o': 'No such file or directory'
1 error generated.
make: *** [bin/2048.o] Error 1

**Comment by nneonneo** [comment]
Try "mkdir bin". The "Permission denied" error is pretty weird - what OS
are you running this with?

**Comment by kgcrandn** [comment]
I am running it with OS X. I try "mkdir bin", and it works. Thanks.
But I am confused why it goes wrong?

**Comment by nneonneo** [comment]
I didn't realize that macOS's default `mkdir` wasn't acceptable to my configure script - I always have the GNU coreutils installed. When `mkdir` isn't acceptable, it falls back to `install-sh`, which wasn't properly executable (it is now).
