### ISSUE TITLE
Taking slower

### ISSUE THREAD

**Issue by lordwayden** [nneonneo/2048-ai#48]
Hello!
First of all, this soft really great!)) 👍  Thanks for it!))
My question is: "How to make it slower? or Where and what I need to write to set step time? "

Thank you! :)

**Comment by nneonneo** [comment]
If you're using the Python code, you can add a delay in the [2048.py play_game function](https://github.com/nneonneo/2048-ai/blob/master/2048.py#L88). If using the C++ code, add a delay to `find_best_move`.
