### ISSUE TITLE
Using the bitboard representation for other AI

### ISSUE THREAD

**Issue by nadhirajk** [nneonneo/2048-ai#49]
Hi Robert, I am writing my undergraduate math thesis on AI for 2048. So far, I have been using my own implementation of the board, but I want to try out more computationally intensive algorithms and would like to use your efficient bit representation of the board, along with the look-up table. I tried to implement it on my own in Python, but could get nowhere near your efficiency. I am unfamiliar with C and new to Github. I'm sorry if this is a trivial issue but I have spent dozens of hours on this already and found no easy answers. 

How can I use your board implementation with different AI? What parts of the repository would I have to fork and what parts would I have to change? I have been trying to understand (only) 2048.py and use parts of that but could not get it to work. Am I ignoring some dependencies? If you could either explain your code a little bit more or tell me how to use your implementation with my own AI it would really save me a huge amount of time and effort. Thank you anyway!

**Comment by nneonneo** [comment]
2048.py depends on the C++ component (2048.cpp) to be built - please build it first according to the instructions (under [Building](https://github.com/nneonneo/2048-ai#building)). 2048.py itself is only a driver, and contains no significant game logic or AI logic. Pretty much all the interesting stuff in this repository is in 2048.cpp.

**Comment by nadhirajk** [comment]
So if I have 2048.ccp and want to use it to test AI written in Python, what would I have to do?

**Comment by nneonneo** [comment]
I don’t understand what you’re asking. If you already have an AI in Python, what do you need the C++ AI for?
