### ISSUE TITLE
Evaluating/PLaying custom boards

### ISSUE THREAD

**Issue by Stochastic13** [nneonneo/2048-ai#52]
Hi!
Thanks for the excellent programme. I'm trying to understand various state-evaluation strategies, and would love to use your ai for the same. Is there a way to make the AI play custom boards and store its recommended move for all of them? Something like inputting a csv of board-states and outputting a csv of recommended moves?

Thank you.

**Comment by nneonneo** [comment]
The `find_best_move` function from 2048.py is the easiest way to get this information. Hand it a board (a 4x4 list-of-lists or 2D NumPy array) containing the board state, with values 1-15 for 2 to 32768, and 0 for empty. It will return the best move, with 0=up, 1=down, 2=left, 3=right.
