### ISSUE TITLE
Issues in find_best_move with numpy arrays

### ISSUE THREAD

**Issue by Stochastic13** [nneonneo/2048-ai#53]
Hi!
I started using `find_best_move` in 2048.py as discussed in issue#52. There are some possible bugs (or perhaps functionalities I am not aware of) when using `numpy` 2d arrays with that function. I have tried to mention everything I tried to do about it and the fix which seems to work.

Prep:
```
import numpy as np
import random
import copy
import importlib.util
spec = importlib.util.spec_from_file_location("2048", "filepath\\2048.py")
aimain = importlib.util.module_from_spec(spec)
spec.loader.exec_module(aimain)
```
When this board-state crops up in the binary version running by itself.
![image](https://user-images.githubusercontent.com/28253514/40912209-84eb2b9a-680e-11e8-91f3-5267b5ff3cd0.png)

1. ## `MULTITHREAD` is `True`

![image](https://user-images.githubusercontent.com/28253514/40912120-49c9678e-680e-11e8-8663-fbf817ea030d.png)

In this case, when the same board state is run through the `find_best_move` function and when it crops up in the normal execution of 2048.exe (or equivalent binary), we get different scores for the different moves, but the printed board seems the same. The one in the binary seems to be the correct version.

2. ## `MULTITHREAD` is `False`

![image](https://user-images.githubusercontent.com/28253514/40912266-b3589c56-680e-11e8-9989-b3b09d0d8cb3.png)

In this case, the scores from the function are still inaccurate but now we do get a different board printed. The scores obtained seem to be correct for the board printed and hence I assume there might be some error in parsing a `numpy` 2d-list. 

3. ## `tolist()`

![image](https://user-images.githubusercontent.com/28253514/40912318-d142eb68-680e-11e8-962f-a8fc69283c87.png)

Using the numpy method `tolist()` seems to have fixed the issue as far as I tested on some hand-coded examples with` MULTITHREAD False.`

I am not sure this arises because of some version mismatch. I am using 32-bit python 3.6 on Windows 10 with most libraries upgraded to the latest version. Used Visual Studio latest version for compiling the binary.

**Comment by Stochastic13** [comment]
Thanks for the response!
I originally used a 32-bit VS command prompt to compile. Will recompile as a 64-bit version.
For the `importlib` part, I was trying to run this from a different directory initially and then did not change the import statements later on.

**Comment by nneonneo** [comment]
To run from a different directory, you can append to sys.path and then do
__import__.
