### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bojosos** [nneonneo/2048-ai#55]
Add a license

**Comment by nneonneo** [comment]
I would like to license this under MIT, however, to add a license I need the sign-off of existing contributors to be on the safe side.

@mtonsmann @m9710797 @xificurk @Ill1 @VrIgHtEr Please all confirm if you are OK with licensing the project under MIT.

**Comment by VrIgHtEr** [comment]
I'm ok with it

**Comment by xificurk** [comment]
I'm fine with that.

**Comment by Ill1** [comment]
Go for it.

**Comment by m9710797** [comment]
Fine for me.

**Comment by mtonsmann** [comment]
fine with me

**Comment by nneonneo** [comment]
Thanks everyone for your quick responses!
