### ISSUE TITLE
Make it compatible with Windows

### ISSUE THREAD

**Issue by AlexanderBiryuckoff** [nneonneo/2048-ai#57]
How can I make it compatible with Windows not using cygwin? Probably i have to create .dll file instead of .so file which the cygwin makes from your cpp & h files. How can I do it? (i'm not good at c++ enough to understand it myself) And what else have i to do?

**Comment by nneonneo** [comment]
You’ll need Visual Studio. Open a command prompt using the VS Tools shortcut (in the start menu), and run make-msvc.bat from the 2048 directory.
