### ISSUE TITLE
Error with ff plugin

### ISSUE THREAD

**Issue by AlexanderBiryuckoff** [nneonneo/2048-ai#58]
When i tried to open your .xpi file with ff, it said: "This add-on cannot be installed since it appears to be damaged." What can i do to fix this problem?

**Comment by nneonneo** [comment]
I just pushed f5797579369147248bec78cd6ae5f97ce6771c08, which enables support for Firefox's native remote debugging protocol. This deprecates the remote-control extension, so you won't need to install that anymore.
