### ISSUE TITLE
What have I to input for "Selection?" question?

### ISSUE THREAD

**Issue by AlexanderBiryuckoff** [nneonneo/2048-ai#59]
In chromectrl line 29 it ask user to input the selection. http://skrinshoter.ru/i/080519/dxCW55.png
What have I to input?

**Comment by nneonneo** [comment]
You’ll need to have the 2048 site open in a tab first, then you will start the bot and input the ID of the tab containing the game (should be identifiable by the tab in the menu - you might need to scroll up to see all options).

**Comment by nneonneo** [comment]
Not sure what's going on there, but I noticed you're using Python 3 so I just pushed a change for Python 3 compatibility.

**Comment by AlexanderBiryuckoff** [comment]
I found a mistake. It worked without errors only because somewhen i added .so library from cygwin, and it doesn't work under windows. Dll lib doesn't work because it has another bitness than python. I'll try to fix it.
