### ISSUE TITLE
Error while trying to run program through Chrome browser

### ISSUE THREAD

**Issue by googolplexxx** [nneonneo/2048-ai#61]
Hi, I'm getting this error when i try to run "python 2048.py -b chrome" in anaconda prompt.
![image](https://user-images.githubusercontent.com/56499911/71553595-477fc800-2a23-11ea-8def-a1fbdd9a366e.png)
 I don't know what is it, please help me to solve this issue.

**Comment by nneonneo** [comment]
Your Python and the 2048 DLL were probably compiled for different bit-ness (for example, Python is 32-bit and the DLL is 64-bit, or the other way around). Try compiling the DLL using the other bit-ness (using the other command-line tools).

**Comment by nneonneo** [comment]
The most likely cause is that your Python and the 2048 DLL were compiled with different compilers, or with different “bit ness” (e.g. Python is 32-bit while 2048.dll is 64-bit, or vice-versa). You can try fixing the issue by recompiling using a different set of command-line tools. 

You can check your Python’s bit-ness by running `python -c 'import struct; print( 8 * struct.calcsize("P"))'`. This will print 32 on a 32-bit Python and 64 on a 64-bit Python.
