### ISSUE TITLE
Error while trying to run program through Firefox browser

### ISSUE THREAD

**Issue by DeafBonce30** [nneonneo/2048-ai#63]
![error](https://user-images.githubusercontent.com/65008103/81378738-deb70380-9118-11ea-90c6-4e9657e28f2c.jpg)
KeyError: 'title' plz help!
Firefox browser with activatade remote debugging and started with firefox --start-debugger-server 32000. After start "python 2048.py -b firefox" i have request in browser to access to remote debugging, clicked YES and giving error in bat file (see screenshot)

**Comment by nneonneo** [comment]
Thanks for the bug report. Firefox changed their debug protocol (seems to have landed some time in the last few months?). Should be fixed now - give it a shot.

**Comment by DeafBonce30** [comment]
Thx! it works! but doesnt work in this site https://2048c.spasibosb.ru/

**Comment by DeafBonce30** [comment]
> Thanks for the bug report. Firefox changed their debug protocol (seems to have landed some time in the last few months?). Should be fixed now - give it a shot.

Thx! it works! but doesnt work in this site https://2048c.spasibosb.ru/

**Comment by nneonneo** [comment]
Sorry, it only works in the original 2048 game (https://play2048.co/) and clones thereof. That site looks like it might be a custom implementation. I can't even try it on the site you posted because it looks like you have to login with a Russian phone number (and I can't read Russian).

That said - if you can figure out how to extract the board state using the developer console, you can put that code into `gamectrl.py` to automate the game. This will require some more legwork though :)

**Comment by DeafBonce30** [comment]
TypeError: Expected string or buffer. Where i can found code of this buffer? Inspector, console or debugger? In the "debugger" tab we have - (index), app.js, jquery-3.4.1.min.js and sberid-deeplink.min.js. Where is can i search it? i am not a programmer......help plz if u can
[(index).txt](https://github.com/nneonneo/2048-ai/files/4607808/index.txt)
[jquery.txt](https://github.com/nneonneo/2048-ai/files/4607809/jquery.txt)
[sberid.txt](https://github.com/nneonneo/2048-ai/files/4607810/sberid.txt)
![1](https://user-images.githubusercontent.com/65008103/81529056-0ef7df80-936f-11ea-937b-a5e09bbb475b.jpg)
![2](https://user-images.githubusercontent.com/65008103/81529063-10290c80-936f-11ea-9e40-e25e98752c2f.jpg)

**Comment by nneonneo** [comment]
I guess it’s in app.js - none of the other files look related, and index refers to app.js through a dynamic script load.

**Comment by DeafBonce30** [comment]
so, i cant fix it....right?)

**Comment by DeafBonce30** [comment]
when i started 2048.py, 1 time moved on top than error, again stard 2048.py and 1 time top move again. Maybe it can help.

**Comment by nneonneo** [comment]
The move is part of a "trick" which the script uses to hook the game's internal state. The fact that the board moved means that this trick failed - which, again, is not surprising because this game is not based on the original 2048 game's code. I'm afraid there's no much I'm going to be able to do.

**Comment by nneonneo** [comment]
Yeah, sorry. I took a look and it’s probably too much work to support this site for not enough of a benefit. They’re using a custom implementation that wouldn’t apply to any other online implementations. Plus, the point of this project is to demonstrate the AI techniques, not to be a bot, so supporting implementations beyond the original would be out of scope. 

If you really want it supported, email me (nneonneo at gmail dot com) and we can chat about it further.
