### ISSUE TITLE
 how does the cut-off function works

### ISSUE THREAD

**Issue by hyper-zlc** [nneonneo/2048-ai#66]
Hi!u
I'm studying your code and the recurse part is really hard for me.After days of work I can understand the whole logic a little,but cut-off part still confuse me,the code `trans_table_entry_t entry = i->second;` in function `score_tilechoose_node`
please explain why  use **board's next** instead of  **board** to compare with current depth?
Thanks!

**Comment by nneonneo** [comment]
`trans_table` is the [transposition table](https://en.wikipedia.org/wiki/Transposition_table) which records seen positions (`board_t`) and maps them to transposition entries (`trans_table_entry_t`). If a position is in the table (cache), it means that the position currently being evaluated was already reached by a different set of moves. The depth of that other position is used to determine if the other position's heuristic score is accurate enough for evaluation of the current node (for example: if two 2s spawn, it might result in the same board as a single 4 spawning, which would make the resulting boards unequal in search depth). There is no "next" board here: in C++, `i->second` is used to grab the `trans_table_entry_t` from the table's iterator (the entry corresponding to the `board` passed to `find`).

**Comment by hyper-zlc** [comment]
thank you very much!
