### ISSUE TITLE
Problems with building on Ubuntu

### ISSUE THREAD

**Issue by HHDang1304** [nneonneo/2048-ai#68]
> ./configure make
configure: WARNING: you should use --build, --host, --target
checking for make-g++... no
checking for make-c++... no
checking for make-gpp... no
checking for make-aCC... no
checking for make-CC... no
checking for make-cxx... no
checking for make-cc++... no
checking for make-cl.exe... no
checking for make-FCC... no
checking for make-KCC... no
checking for make-RCC... no
checking for make-xlC_r... no
checking for make-xlC... no
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for make-gcc... no
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for make-gcc... gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking unordered_map usability... yes
checking unordered_map presence... yes
checking for unordered_map... yes
checking tr1/unordered_map usability... yes
checking tr1/unordered_map presence... yes
checking for tr1/unordered_map... yes
checking for inline... inline
checking for uint16_t... yes
checking for uint64_t... yes
checking for gettimeofday... yes
checking for strchr... yes
checking for arc4random_uniform... no
checking for drand48... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: error: cannot find input file: `config.h.in'

Hello, I'm new to C++ so I'm not sure if I did correctly. I followed your instruction and got this error
Do I need to run **autoconf** before **./configure make** Even so, I got another problem:

> ./configure make
configure: WARNING: you should use --build, --host, --target
./configure: line 2246: syntax error near unexpected token `,'
./configure: line 2246: `AX_CXX_COMPILE_STDCXX_11(, optional)'

I guess it is due to version incompatibility?

**Comment by nneonneo** [comment]
Try `./configure` and `make` as *separate* commands, not as part of the same command.
