### ISSUE TITLE
About all the constant numbers you set

### ISSUE THREAD

**Issue by duongnc000** [nneonneo/2048-ai#69]
My class are doing a project about 2048 AI so I want to research some 2048 AI. So if you can, can you explain how did you get all the constant number from Score_lost_penalty, Score_monotonicty_power, etc.?

**Comment by nneonneo** [comment]
Thanks for asking! The constants were optimized by Petr Morávek (@xificurk) using a technique known as CMA-ES. You can get a bit more detail at the StackOverflow post (https://stackoverflow.com/a/22498940/1204143) or by perusing the history of this repository.
