### ISSUE TITLE
Looking forward to CUDA version?

### ISSUE THREAD

**Issue by z0z0r4** [nneonneo/2048-ai#70]
I found you say this on stackoverflow
```
Currently porting to Cuda so the GPU does the work for even better speeds! – 
[nimsson](https://stackoverflow.com/users/2246612/nimsson)
 [Apr 11, 2014 at 21:54](https://stackoverflow.com/questions/22342854/what-is-the-optimal-algorithm-for-the-game-2048/22498940#comment35171260_22498940)
```

**Comment by z0z0r4** [comment]
i don't why it is so slow on my PC...sometimes 0.2step/sec or less 
![image](https://user-images.githubusercontent.com/78744121/183335232-3ff4c07d-acb6-4cad-ab7f-05a55564c79e.png)

I5-9300H

**Comment by nneonneo** [comment]
1. The comment about CUDA is not from me - that’s a different commenter. I don’t know whether they ended up making a CUDA version. 
2. The AI “thinks harder” when the board is especially full, as these when making the right move is crucial. There’s a heuristic that tunes the depth of the expectimax search which depends on the number of empty squares, etc. The slowdown is usually just for a few moves before a big chain of merges; it should speed up after the board clears.

**Comment by z0z0r4** [comment]
oh, I am sorrrry! 
[nneonneo](https://github.com/nneonneo) != nimsson
hmmm, may be, but during 4096~8192, it took long long time

**Comment by z0z0r4** [comment]
看起来是这样的，当即将能够合出一个较大的数字，他会将搜索深度设为7

It looks like this, when it is about to be able to make a larger number, he will set the search depth to 7

**Comment by WuDi-ZhanShen** [comment]
> 看起来是这样的，当即将能够合出一个较大的数字，他会将搜索深度设为7
> 
> It looks like this, when it is about to be able to make a larger number, he will set the search depth to 7

思考深度由当前棋盘上有多少种类的数字决定。比如当前棋盘充满了2，4，8，这个时候数字种类只有3种，相应的思考深度也只有3层；如果棋盘上有很多数字，那么思考深度就相应提升
