### ISSUE TITLE
能不能考虑加一个非网页版的2014ai

### ISSUE THREAD

**Issue by jinghuashang** [nneonneo/2048-ai#72]
比如windows环境下的2048

**Comment by nneonneo** [comment]
It should be possible; the core `gamectrl` abstraction is fairly generic and could be edited to support other games. However, you would have to solve the problem of getting the game board state from the app (e.g. by inspecting process memory, or OCRing the GUI), and of providing input to the app (e.g. by using AutoHotKey or some kind of Java AWT Robot shim).

Unfortunately, I cannot personally support implementing this for some specific app.
